import 'dart:ui';

import 'package:firebase_analytics/firebase_analytics.dart';

String getColumnAbb(String value) {
  if (constantColumns.containsKey(value)) {
    return constantColumns[value];
  }
  _sendEvent('abb_not_found', {
    'abb': value
  });
  print('abb $value');
  return 'UNK';
}

String getColumnTooltip(String value) {
  if (constantTooltips.containsKey(value)) {
    return constantTooltips[value];
  }
  _sendEvent('tooltip_not_found', {
    'tooltip': value
  });
  print('tooltip: $value');
  return 'UNK';
}

Future<Null> _sendEvent(String name, Map<String, String> params) async {
  await FirebaseAnalytics().logEvent(name: name, parameters: params);
}

const Map<String, String> constantColumns = {
  'assists': 'A',
  'birthDate': 'DOB',
  'currentTeamAbbrev': 'Team',
  'faceoffLosses': 'FOL',
  'faceoffWinPct': 'FOW%',
  'faceoffWins': 'FOW',
  'faceOffWins': 'FOW',
  'faceoffsLost': 'FOL',
  'faceoffsWon': 'FOW',
  'franchiseName': 'Team',
  'gameDate': 'Game Date',
  'gameId': 'Game',
  'gameWinningGoals': 'GWG',
  'games': 'GP',
  'gamesPlayed': 'GP',
  'gamesStarted': 'GS',
  'goalieFullName': 'Player',
  'goals': 'G',
  'goalAgainstAverage': 'GAA',
  'goalsAgainst': 'GA',
  'goalsAgainstPerGame': 'GA/GP',
  'goalsFor': 'GF',
  'goalsForPerGame': 'GF/GP',
  'homeRoad': 'Game Location',
  'lastName': 'Player',
  'losses': 'L',
  'opponentTeamAbbrev': 'Opp Team',
  'overTimeGoals': 'OTG',
  'otGoals': 'OTG',
  'ot': 'OT',
  'otLosses': 'OT',
  'otPoints': 'OTP',
  'penaltyKillPct': 'PK%',
  'pim': 'PIM',
  'penaltyMinutes': 'PIM',
  'pkPctg': 'PK%',
  'playerTeamsPlayedFor': 'Team',
  'plusMinus': '+/-',
  'pointPct': 'P%',
  'points': 'P',
  'pointsPerGame': 'P/GP',
  'positionCode': 'Pos',
  'powerPlayPct': 'PP%',
  'powerPlayGoals': 'PPG',
  'ppGoals': 'PPG',
  'ppGoalsAgainst': 'PP GA',
  'ppOpportunities': 'PP Opp',
  'ppPctg': 'PP%',
  'powerPlayPoints': 'PPP',
  'ppPoints': 'PPP',
  'regulationAndOtWins': 'ROW',
  'savePercentage': 'Sv%',
  'savePct': 'Sv%',
  'seasonId': 'Season',
  'shortHandedGoals': 'SHG',
  'shortHandedAssists': 'SHA',
  'shGoals': 'SHG',
  'shNumTimes': 'TS',
  'shortHandedPoints': 'SHP',
  'shPoints': 'SHP',
  'shiftsPerGame': 'Shifts/GP',
  'shotPct': 'S%',
  'shootingPct': 'S%',
  'shootingPctg': 'S%',
  'shootoutLosses': 'S/O Loss',
  'shootoutWins': 'S/O Win',
  'shootsCatches': 'S/C',
  'shots': 'S',
  'saves': 'Svs',
  'shortHandedShots': 'SH SA',
  'shortHandedSaves': 'SH Svs',
  'shortHandedShotsAgainst': 'SH SA',
  'shortHandedSavePercentage': 'SH Sv%',
  'powerPlaySaves': 'PP Svs',
  'powerPlayShots': 'PP SA',
  'powerPlayShotsAgainst': 'PP SA',
  'powerPlaySavePercentage': 'PP Sv%',
  'evenSaves': 'EV Svs',
  'evenShots': 'EV SA',
  'evenShotsAgainst': 'EV SA',
  'evenStrengthSavePercentage': 'EV Sv%',
  'shotsAgainst': 'SA',
  'shotsAgainstPerGame': 'SA/GP',
  'shotsFor': 'SF',
  'shotsForPerGame': 'Shots/GP',
  'shutouts': 'SO',
  'skaterFullName': 'Player',
  'teamAbbrev': 'Team',
  'teamAbbrevs': 'Team',
  'teamFullName': 'Team',
  'ties': 'T',
  'timeOnIce': 'TOI',
  'timeOnIcePerGame': 'TOI/GP',
  'timeOnIcePerGame5v5': '5v5 TOI/GP',
  'timesShorthanded': 'TS',
  'totalFaceoffLosses': 'FOL',
  'totalFaceoffWins': 'FOW',
  'wins': 'W',
  'winsInRegulation': 'RW',
  'winsInShootout': 'S/O Win',
  'defensiveZoneFaceoffLosses': 'DZ FOL',
  'defensiveZoneFaceoffWins': 'DZ FOW',
  'defensiveZoneFaceoffs': 'DZ FO',
  'evFaceoffs': 'EV FO',
  'evFaceoffsLost': 'EV FOL',
  'evFaceoffsWon': 'EV FOW',
  'neutralZoneFaceoffLosses': 'NZ FOL',
  'neutralZoneFaceoffWins': 'NZ FOW',
  'neutralZoneFaceoffs': 'NZ FO',
  'offensiveZoneFaceoffLosses': 'OZ FOL',
  'offensiveZoneFaceoffWins': 'OZ FOW',
  'offensiveZoneFaceoffs': 'OZ FO',
  'ppFaceoffs': 'PP FO',
  'ppFaceoffsLost': 'PP FOL',
  'ppFaceoffsWon': 'PP FOW',
  'shFaceoffs': 'SH FO',
  'shFaceoffsLost': 'SH FOL',
  'shFaceoffsWon': 'SH FOW',
  'totalFaceoffs': 'FO',
  'faceoffTaken': 'FO',
  'evGoals': 'EVG',
  'evPoints': 'EVP',
  'blocked': 'BkS',
  'blockedShots': 'BkS',
  'blockedShotsPer60': 'BkS/60',
  'emptyNetAssists': 'ENA',
  'emptyNetGoals': 'ENG',
  'emptyNetPoints': 'ENP',
  'firstGoals': '1g',
  'giveaways': 'GvA',
  'giveawaysPer60': 'GvA/60',
  'hits': 'Hits',
  'hitsPer60': 'Hits/60',
  'missedShotCrossbar': 'MsS Cross',
  'missedShotGoalpost': 'MsS Post',
  'missedShotOverNet': 'MsS Over',
  'missedShotWideOfNet': 'MsS Wide',
  'missedShots': 'MsS',
  'takeaways': 'TkA',
  'takeawaysPer60': 'TkA/60',
  'ppAssists': 'PPA',
  'powerPlayAssists': 'PPA',
  'ppGoalsForPer60': 'PP GF/60',
  'ppGoalsPer60': 'PPG/60',
  'ppIndividualSatFor': 'PP iSAT',
  'ppIndividualSatForPer60': 'PP iSAT/60',
  'ppPointsPer60': 'PPP/60',
  'ppPrimaryAssists': 'PPA1',
  'ppPrimaryAssistsPer60': 'PPA1/60',
  'ppSecondaryAssists': 'PPA2',
  'ppSecondaryAssistsPer60': 'PPA2/60',
  'ppShootingPct': 'PP S%',
  'ppShots': 'PP Shots',
  'ppShotsPer60': 'PP S/60',
  'powerPlayTimeOnIce': 'PP TOI',
  'ppTimeOnIce': 'PP TOI',
  'ppTimeOnIcePctPerGame': 'PP TOI%',
  'ppTimeOnIcePerGame': 'PP TOI/GP',
  'evenTimeOnIce': 'EV TOI',
  'evTimeOnIce': 'EV TOI',
  'evenTimeOnIcePerGame': 'EV TOI/GP',
  'evTimeOnIcePerGame': 'EV TOI/GP',
  'otTimeOnIce': 'OT TOI',
  'otTimeOnIcePerOtGame': 'OT TOI/OT GP',
  'shTimeOnIce': 'SH TOI',
  'shTimeOnIcePerGame': 'SH TOI/GP',
  'shifts': 'Shifts',
  'defensiveZoneFaceoffPct': 'DZ FOW%',
  'evFaceoffPct': 'EV FOW%',
  'neutralZoneFaceoffPct': 'NZ FOW%',
  'offensiveZoneFaceoffPct': 'OZ FOW%',
  'ppFaceoffPct': 'PP FOW%',
  'shFaceoffPct': 'SH FOW%',
  'faceOffPct': 'FO%',
  'goalsBackhand': 'G Back',
  'goalsDeflected': 'G Def',
  'goalsSlap': 'G Slap',
  'goalsSnap': 'G Snap',
  'goalsTipIn': 'G Tip',
  'goalsWrapAround': 'G Wrap',
  'goalsWrist': 'G Wrist',
  'shootingPctBackhand': 'S% Back',
  'shootingPctDeflected': 'S% Def',
  'shootingPctSlap': 'S% Slap',
  'shootingPctSnap': 'S% Snap',
  'shootingPctTipIn': 'S% Tip',
  'shootingPctWrapAround': 'S% Wrap',
  'shootingPctWrist': 'S% Wrist',
  'shotsOnNetBackhand': 'S Back',
  'shotsOnNetDeflected': 'S Def',
  'shotsOnNetSlap': 'S Slap',
  'shotsOnNetSnap': 'S Snap',
  'shotsOnNetTipIn': 'S Tip',
  'shotsOnNetWrapAround': 'S Wrap',
  'shotsOnNetWrist': 'S Wrist',
  'evenStrengthGoalDifference': 'On-Ice EV GD',
  'evenStrengthGoalsAgainst': 'On-Ice EV GA',
  'evenStrengthGoalsFor': 'On-Ice EV GF',
  'evenStrengthGoalsForPct': 'On-Ice EV GF%',
  'evenStrengthTimeOnIcePerGame': 'EV TOI/GP',
  'powerPlayGoalFor': 'On-Ice PP GF',
  'powerPlayGoalsAgainst': 'On-Ice PP GA',
  'powerPlayTimeOnIcePerGame': 'PP TOI/GP',
  'shortHandedGoalsAgainst': 'On-Ice SH GA',
  'shortHandedGoalsFor': 'On-Ice SH GF',
  'shortHandedTimeOnIcePerGame': 'SH TOI/GP',
  'shortHandedTimeOnIce': 'SH TOI',
  'faceoffsWo': 'FOW',
  'winsInRegulatio': 'RW',
  'penaltyKillNetPct': 'Net PK%',
  'powerPlayNetPct': 'Net PP%',
  'lossesScoringFirst': 'L SF',
  'lossesTrailingFirst': 'L TF',
  'otLossesScoringFirst': 'OT SF',
  'otLossesTrailingFirst': 'OT TF',
  'scoringFirstGamesPlayed': 'SF GP',
  'tiesScoringFirst': 'T SF',
  'tiesTrailingFirst': 'T TF',
  'trailingFirstGamesPlayed': 'TF GP',
  'winPctScoringFirst': 'W% SF',
  'winPctTrailingFirst': 'W% TF',
  'winsScoringFirst': 'W SF',
  'winsTrailingFirst': 'W TF',
  "lossLeadPeriod1": "Loss Lead 1P",
  "lossLeadPeriod2": "Loss Lead 2P",
  "lossTrailPeriod1": "Loss Trail 1P",
  "lossTrailPeriod2": "Loss Trail 2P",
  "otLossLeadPeriod1": "OT Loss Lead 1P",
  "otLossLeadPeriod2": "OT Loss Lead 2P",
  "otLossTrailPeriod1": "OT Loss Trail 1P",
  "otLossTrailPeriod2": "OT Loss Trail 2P",
  "period1GoalsAgainst": "GA in P1",
  "period1GoalsFor": "GF in P1",
  "period2GoalsAgainst": "GA in P2",
  "period2GoalsFor": "GF in P2",
  "tiesLeadPeriod1": "Ties Lead 1P",
  "tiesLeadPeriod2": "Ties Lead 2P",
  "tiesTrailPeriod1": "Ties Trail 1P",
  "tiesTrailPeriod2": "Ties Trail 2P",
  "winPctLeadPeriod1": "Win% Lead 1P",
  "winPctLeadPeriod2": "Win% Lead 2P",
  "winPctTrailPeriod1": "Win% Trail 1P",
  "winPctTrailPeriod2": "Win% Trail 2P",
  "winsLeadPeriod1": "Wins Lead 1P",
  "winsLeadPeriod2": "Wins Lead 2P",
  "winsTrailPeriod1": "Wins Trail 1P",
  "winsTrailPeriod2": "Wins Trail 2P",
  'lossesEvenShots': 'Loss Even Shots',
  'lossesOutshootOpponent': 'Loss Outshoot Opp',
  'lossesOutshotByOpponent': 'Loss Outshot by Opp',
  'netShotsPerGame': 'SD/GP',
  'otLossesEvenShots': 'OT Loss Even Shots',
  'otLossesOutshootOpponent': 'OT Loss Outshoot Opp',
  'otLossesOutshotByOpponent': 'OT Loss Outshot by Opp',
  'tiesEvenShots': 'Ties Even Shots',
  'tiesOutshootOpponent': 'Ties Outshoot Opp',
  'tiesOutshotByOpponent': 'Ties Outshot by Opp',
  'winsEvenShots': 'Wins Even Shots',
  'winsOutshootOpponent': 'Wins Outshoot Opp',
  'winsOutshotByOpponent': 'Wins Outshot by Opp',
  'homeRecord': 'HOME',
  'awayRecord': 'AWAY',
  'soRecord': 'S/O',
  'l10Record': 'L10',
  'streak': 'STRK',
  'gameMisconductPenalties':'G Msct',
  'majorPenalties':'Major',
  'matchPenalties':'Match',
  'minorPenalties':'Minor',
  'misconductPenalties':'Msct',
  'netPenalties':'Net Pen',
  'netPenaltiesPer60':'Net Pen/60',
  'penalties':'Pen Taken',
  'penaltiesDrawn':'Pen Drawn',
  'penaltiesDrawnPer60':'Pen Drawn/60',
  'penaltiesTakenPer60':'Pen Taken/60',
  'penaltyMinutesPerTimeOnIce':'PIM/TOI%',
  'penaltySecondsPerGame':'PIM/GP',
  'ppGoalsAgainstPer60':'PP GA/60',
  'shAssists':'SHA',
  'shGoalsPer60':'SHG/60',
  'shIndividualSatFor':'SH iSAT',
  'shIndividualSatForPer60':'SH iSAT/60',
  'shPointsPer60':'SHP/60',
  'shPrimaryAssists':'SHA1',
  'shPrimaryAssistsPer60':'SHA1/60',
  'shSecondaryAssists':'SHA2',
  'shSecondaryAssistsPer60':'SHA2/60',
  'shShootingPct':'SH S%',
  'shShots':'SH Shots',
  'shShotsPer60':'SH S/60',
  'shTimeOnIcePctPerGame':'SH TOI%',
  'penaltyShotAttempts':'PS Att',
  'penaltyShotShootingPct':'PS S%',
  'penaltyShotsFailed':'PS F',
  'penaltyShotsGoals':'PS G',
  'faceoffPct5v5':'FOW%',
  'goalsPct':'On-Ice GF %',
  'individualSatForPer60':'iSAT/60',
  'individualShotsForPer60':'5v5 S/60',
  'onIceShootingPct':'On-Ice S%',
  'satPct':'SAT%',
  'usatPct':'USAT %',
  'zoneStartPct':'OZ%','satAgainst':'SAT Agst',
  'satAhead':'SAT Ahead',
  'satBehind':'SAT Behind',
  'satClose':'SAT Close',
  'satFor':'SAT For',
  'satRelative':'SAT% Relative',
  'satTied':'SAT Tied',
  'satTotal':'SAT',
  'usatAgainst':'USAT Agst',
  'usatAhead':'USAT Ahead',
  'usatBehind':'USAT Behind',
  'usatClose':'USAT Close',
  'usatFor':'USAT For',
  'usatRelative':'USAT% Relative',
  'usatTied':'USAT Tied',
  'usatTotal':'USAT',
  'satPercentage':'SAT%',
  'satPercentageAhead':'SAT% Ahead',
  'satPercentageBehind':'SAT% Behind',
  'satPercentageClose':'SAT% Close',
  'satPercentageTied':'SAT% Tied',
  'shootingPct5v5':'On-Ice S%',
  'skaterSavePct5v5':'On-Ice Sv%',
  'skaterShootingPlusSavePct5v5':'On-Ice S%+Sv%',
  'usatPercentage':'USAT%',
  'usatPercentageAhead':'USAT% Ahead',
  'usatPercentageBehind':'USAT% Behind',
  'usatPercentageTied':'USAT% Tied',
  'usatPrecentageClose':'USAT% Close',
  'zoneStartPct5v5':'OZ%',
  'assists5v5':'A',
  'assistsPer605v5':'A/60',
  'goals5v5':'G',
  'goalsPer605v5':'G/60',
  'netMinorPenaltiesPer60':'Net Minors/60',
  'offensiveZoneStartPct5v5':'OZ%',
  'onIceShootingPct5v5':'On-Ice S%',
  'points5v5':'P',
  'pointsPer605v5':'P/60',
  'primaryAssists5v5':'A1',
  'primaryAssistsPer605v5':'A1/60',
  'satRelative5v5':'SAT Rel%',
  'secondaryAssists5v5':'A2',
  'secondaryAssistsPer605v5':'A2/60',
  'assistsPerGame':'A/GP',
  'blocksPerGame':'BkS/GP',
  'goalsPerGame':'G/GP',
  'hitsPerGame':'Hits/GP',
  'penaltyMinutesPerGame':'PIM/GP',
  'primaryAssistsPerGame':'A1/GP',
  'secondaryAssistsPerGame':'A2/GP',
  'shotsPerGame':'S/GP',
  'totalPrimaryAssists':'A1',
  'totalSecondaryAssists':'A2',
  'timeOnIcePerShift':'TOI/Shift',
  'goalsAgainstAverage':'GAA',
  'completeGamePct':'CG%',
  'completeGames':'CG',
  'goalsAgainstPerRegulationLoss':'GA / ROL',
  'goalsForAverage':'GFA',
  'incompleteGames':'IG',
  'qualityStart':'GS > .900',
  'qualityStartsPct':'GS > .900 %',
  'regulationLosses':'ROL',
  'regulationWins':'ROW',
  'shotsAgainstPer60':'SA/60',
  'gamesPlayedDaysRest0':'0 Days Rest',
  'gamesPlayedDaysRest1':'1 Days Rest',
  'gamesPlayedDaysRest2':'2 Days Rest',
  'gamesPlayedDaysRest3':'3 Days Rest',
  'gamesPlayedDaysRest4Plus':'4+ Days Rest',
  'savePctDaysRest0':'0 Days Sv%',
  'savePctDaysRest1':'1 Days Sv%',
  'savePctDaysRest2':'2 Days Sv%',
  'savePctDaysRest3':'3 Days Sv%',
  'savePctDaysRest4Plus':'4+ Days Sv%','penaltyShotSavePct':'PS Sv%',
  'penaltyShotsAgainst':'PS SA',
  'penaltyShotsGoalsAgainst':'PS GA',
  'penaltyShotsSaves':'PS Svs',
  'evGoalsAgainst':'EV GA',
  'evSavePct':'EV Sv%',
  'evSaves':'EV Svs',
  'evShotsAgainst':'EV SA',
  'ppSavePct':'PP Sv%',
  'ppSaves':'PP Svs',
  'ppShotsAgainst':'PP SA',
  'shGoalsAgainst':'SH GA',
  'shSavePct':'SH Sv%',
  'shSaves':'SH Svs',
  'shShotsAgainst':'SH SA',
  'gamesRelieved':'GR',
  'gamesRelievedGoalsAgainst':'GR GA',
  'gamesRelievedLosses':'GR L',
  'gamesRelievedOtLosses':'GR OT',
  'gamesRelievedSavePct':'GR Sv %',
  'gamesRelievedSaves':'GR Svs',
  'gamesRelievedShotsAgainst':'GR SA',
  'gamesRelievedTies':'GR T',
  'gamesRelievedWins':'GR W',
  'gamesStartedGoalsAgainst':'GS GA',
  'gamesStartedLosses':'GS L',
  'gamesStartedOtLosses':'GS OT',
  'gamesStartedSavePct':'GS Sv %',
  'gamesStartedSaves':'GS Svs',
  'gamesStartedShotsAgainst':'GS SA',
  'gamesStartedTies':'GS T',
  'gamesStartedWins':'GS W',
  'birthCity':'Birth City',
  'birthCountryCode':'Ctry',
  'birthStateProvinceCode':'S/P',
  'draftOverall':'Overall',
  'draftRound':'Round',
  'draftYear':'Draft Yr',
  'firstSeasonForGameType':'1st Season',
  'height':'Ht',
  'isInHallOfFameYn':'HOF',
  'nationalityCode':'Ntnlty',
  'weight':'Wt',
  "daysRest":"Days Btwn Games",
  "netGoalsPerGame":"GD/GP",
  "ppOpportunitiesPerGame":"PP Opp/GP",
  "shotDifferentialPerGame":"SD/GP",
  "timesShorthandedPerGame":"TS/GP",
  "goalsAgainst3On3":"GA 3v3",
  "goalsAgainst3On4":"GA 3v4",
  "goalsAgainst3On5":"GA 3v5",
  "goalsAgainst3On6":"GA 3v6",
  "goalsAgainst4On3":"GA 4v3",
  "goalsAgainst4On4":"GA 4v4",
  "goalsAgainst4On5":"GA 4v5",
  "goalsAgainst4On6":"GA 4v6",
  "goalsAgainst5On3":"GA 5v3",
  "goalsAgainst5On4":"GA 5v4",
  "goalsAgainst5On5":"GA 5v5",
  "goalsAgainst5On6":"GA 5v6",
  "goalsAgainst6On3":"GA 6v3",
  "goalsAgainst6On4":"GA 6v4",
  "goalsAgainst6On5":"GA 6v5",
  "goalsAgainstPenaltyShots":"PS GA",
  "evGoalsFor":"EV GF",
  "period3GoalsAgainst":"GA in P3",
  "period3GoalsFor":"GF in P3",
  "periodOtGoalsAgainst":"GA in OT",
  "periodOtGoalsFor":"GF in OT",
  "ppGoalsFor":"PP GF",
  "shGoalsFor":"SH GF",
  "goalsFor3On3":"GF 3v3",
  "goalsFor3On4":"GF 3v4",
  "goalsFor3On5":"GF 3v5",
  "goalsFor3On6":"GF 3v6",
  "goalsFor4On3":"GF 4v3",
  "goalsFor4On4":"GF 4v4",
  "goalsFor4On5":"GF 4v5",
  "goalsFor4On6":"GF 4v6",
  "goalsFor5On3":"GF 5v3",
  "goalsFor5On4":"GF 5v4",
  "goalsFor5On5":"GF 5v5",
  "goalsFor5On6":"GF 5v6",
  "goalsFor6On3":"GF 6v3",
  "goalsFor6On4":"GF 6v4",
  "goalsFor6On5":"GF 6v5",
  "goalsForPenaltyShots":"PS GF",
  "benchMinorPenalties":"Bench",
  "gameMisconducts":"G Msct",
  "majors":"Major",
  "minors":"Minor",
  "misconducts":"Msct",
  "totalPenaltiesDrawn":"Pen Drawn",
  "pkNetGoals":"SH GD",
  "pkNetGoalsPerGame":"SH GD/GP",
  "pkTimeOnIcePerGame":"SH TOI/GP",
  "pointsPct":"P%",
  "ppGoalsAgainstPerGame":"PP GA/GP",
  "shGoalsForPerGame":"SH GF/GP",
  "goalsAgainst3v4":"GA 3v4",
  "goalsAgainst3v5":"GA 3v5",
  "goalsAgainst4v5":"GA 4v5",
  "overallPenaltyKillPct":"PK%",
  "penaltyKillPct3v4":"PK% 3v4",
  "penaltyKillPct3v5":"PK% 3v5",
  "penaltyKillPct4v5":"PK% 4v5",
  "shorthandedGoalsAgainst":"SH GA",
  "timeOnIce3v4":"TOI 3v4",
  "timeOnIce3v5":"TOI 3v5",
  "timeOnIce4v5":"TOI 4v5",
  "timeOnIceShorthanded":"SH TOI",
  "timesShorthanded3v4":"TS 3v4",
  "timesShorthanded3v5":"TS 3v5",
  "timesShorthanded4v5":"TS 4v5",
  "powerPlayGoalsFor":"PP GF",
  "ppGoalsPerGame":"PP GF/GP",
  "ppNetGoals":"PP GD",
  "ppNetGoalsPerGame":"PP GD/GP",
  "shGoalsAgainstPerGame":"SH GA/GP",
  "goals4v3":"4v3 GF",
  "goals5v3":"5v3 GF",
  "goals5v4":"5v4 GF",
  "opportunities4v3":"4v3 Opp",
  "opportunities5v3":"5v3 Opp",
  "opportunities5v4":"5v4 Opp",
  "overallPowerPlayPct":"PP%",
  "powerPlayPct4v3":"4v3 PP %",
  "powerPlayPct5v3":"5v3 PP %",
  "powerPlayPct5v4":"5v4 PP %",
  "timeOnIce4v3":"4v3 TOI",
  "timeOnIce5v3":"5v3 TOI",
  "timeOnIce5v4":"5v4 TOI",
  "timeOnIcePp":"PP TOI",
  'shots5v5':'Shots 5v5',
  "goalsForPct":"GF%",
  "onIceGoalsAgainst":"GA",
  "onIceGoalsFor":"GF",
  "satPctAhead":"SAT% Ahead",
  "satPctBehind":"SAT% Behind",
  "satPctClose":"SAT% Close",
  "satPctTied":"SAT% Tied",
  "savePct5v5":"5v5 Sv%",
  "shootingPlusSavePct5v5":"5v5 S%+Sv%",
  "usatPctAhead":"USAT% Ahead",
  "usatPctBehind":"USAT% Behind",
  "usatPctClose":"USAT% Close",
  "usatPctTied":"USAT% Tied",
  'shotsOnNet':'S',
  "lossesOneGoalGames":"Loss 1 Goal Game",
  "lossesThreeGoalGames":"Loss 3 Goal Game",
  "lossesTwoGoalGames":"Loss 2 Goal Game",
  "otLossesOneGoalGames":"OT Loss 1 Goal Game",
  "winPctOneGoalGames":"Win% 1 Goal Game",
  "winPctThreeGoalGames":"Win% 3 Goal Game",
  "winPctTwoGoalGames":"Win% 2 Goal Game",
  "winsOneGoalGames":"Wins 1 Goal Game",
  "winsThreeGoalGames":"Wins 3 Goal Game",
  "winsTwoGoalGames":"Wins 2 Goal Game",
};

const Map<String, String> constantTooltips = {
  'assists': 'Assists',
  'birthDate': 'Player Birth Date',
  'currentTeamAbbrev': 'Current Team',
  'defensiveZoneFaceoffLosses': 'Defensive Zone Faceoff Losses',
  'defensiveZoneFaceoffPct': 'Faceoff Win % - Defensive Zone',
  'defensiveZoneFaceoffWins': 'Defensive Zone Faceoff Wins',
  'defensiveZoneFaceoffs': 'Defensive Zone Faceoffs',
  'evFaceoffLosses': 'Even Strength Faceoff Losses',
  'evFaceoffPct': 'Even Strength Faceoff Win %',
  'evFaceoffWins': 'Even Strength Faceoffs Won',
  'evFaceoffs': 'Even Strength Faceoffs',
  'evFaceoffsLost': 'Even Strength Faceoffs Lost',
  'evFaceoffsWon': 'Even Strength Faceoffs Won',
  'faceoffLosses': 'Faceoffs Lost',
  'faceOffWinPercentage': 'Faceoffs Win %',
  'faceoffWinPct': 'Faceoff Win Percentage',
  'faceoffWins': 'Faceoffs Won',
  'faceOffWins': 'Faceoffs Won',
  'faceoffsLost': 'Faceoffs Lost',
  'faceOffsLost': 'Faceoffs Lost',
  'faceoffsWon': 'Faceoffs Won',
  'faceOffsWon': 'Faceoffs Won',
  'franchiseName': 'Team',
  'gameDate': 'Game Date',
  'gameId': 'Game',
  'gameWinningGoals': 'Game Winning Goals',
  'games': 'Games Played',
  'gamesPlayed': 'Games Played',
  'gamesStarted': 'Games Started',
  'goalieFullName': 'Player Name',
  'goals': 'Goals',
  'goalAgainstAverage': 'Goals Against Average',
  'goalsAgainst': 'Goals Against',
  'goalsAgainstPerGame': 'Goals Against Per Game',
  'goalsFor': 'Goals For',
  'goalsPerGame': 'Goals For Per Game',
  'goalsForPerGame': 'Goals For Per Game',
  'homeRoad': 'Home or Road',
  'losses': 'Losses',
  'neutralZoneFaceoffLosses': 'Neutral Zone Faceoff Losses',
  'neutralZoneFaceoffPct': 'Faceoff Win % - Neutral Zone',
  'neutralZoneFaceoffWins': 'Neutral Zone Faceoff Wins',
  'neutralZoneFaceoffs': 'Neutral Zone Faceoffs',
  'offensiveZoneFaceoffLosses': 'Offensive Zone Faceoff Losses',
  'offensiveZoneFaceoffPct': 'Faceoff Win % - Offensive Zone',
  'offensiveZoneFaceoffWins': 'Offensive Zone Faceoff Wins',
  'offensiveZoneFaceoffs': 'Offensive Zone Faceoffs',
  'opponentTeamAbbrev': 'Opponent Team',
  'overTimeGoals': 'Overtime Goals',
  'otGoals': 'Overtime Goals',
  'ot': 'Overtime Losses',
  'otLosses': 'Overtime Losses',
  'otPoints': 'Overtime Points',
  'penaltyKillPct': 'Penalty Kill %',
  'pim': 'Penalty minutes',
  'penaltyMinutes': 'Penalty Minutes',
  'pkPctg': 'Penalty Kill Percentage',
  'playerTeamsPlayedFor': 'Player Teams Played For',
  'plusMinus': 'Plus-Minus',
  'ptPctg': 'Point %',
  'pointPct': 'Point %',
  'pts': 'Points',
  'points': 'Points',
  'pointsPerGame': 'Points Per Game',
  'positionCode': 'Player Position',
  'powerPlayPercentage': 'Power Play %',
  'powerPlayPct': 'Power Play Percentage',
  'ppFaceoffLosses': 'Power Play Faceoffs Lost',
  'ppFaceoffPct': 'Power Play Faceoff Win %',
  'ppFaceoffWins': 'Power Play Faceoffs Won',
  'ppFaceoffs': 'Power Play Faceoffs',
  'ppFaceoffsLost': 'Power Play Faceoffs Lost',
  'ppFaceoffsWon': 'Power Play Faceoffs Won',
  'powerPlayGoals': 'Power Play Goals',
  'ppGoals': 'Power Play Goals',
  'ppGoalsAgainst': 'Power Play Goals Against',
  'powerPlayOpportunities': 'Power Play Opportunities',
  'ppOpportunities': 'Power Play Opportunities',
  'ppPctg': 'Power Play Percentage',
  'powerPlayPoints': 'Power Play Points',
  'ppPoints': 'Power Play Points',
  'regulationAndOtWins': 'Regulation Plus Overtime Wins',
  'savePercentage': 'Save %',
  'savePctg': 'Save %',
  'savePct': 'Save %',
  'seasonId': 'Season',
  'penaltyKillPercentage': 'Penalty Kill %',
  'shFaceoffLosses': 'Shorthanded Faceoffs Lost',
  'shFaceoffPct': 'Shorthanded Faceoff Win %',
  'shFaceoffWins': 'Shorthanded Faceoffs Won',
  'shFaceoffs': 'Shorthanded Faceoffs',
  'shFaceoffsLost': 'Shorthanded Faceoffs Lost',
  'shFaceoffsWon': 'Shorthanded Faceoffs Won',
  'shortHandedGoals': 'Shorthanded Goals',
  'shortHandedAssists': 'Shorthanded Assists',
  'shGoals': 'Shorthanded Goals',
  'shNumTimes': 'Times Shorthanded',
  'shortHandedPoints': 'Shorthanded Points',
  'shPoints': 'Shorthanded Points',
  'shiftsPerGame': 'Shifts Per Game',
  'shotPct': 'Shooting Percentage',
  'shootingPct': 'Shooting Percentage',
  'shootingPctg': 'Shooting Percentage',
  'shootoutLosses': 'Shootout Games Lost',
  'shootoutWins': 'Shootout Games Won',
  'shootsCatches': 'Player Shoots/Catches',
  'shots': 'Shots',
  'saves': 'Saves',
  'shortHandedSaves': 'Shorthanded Saves',
  'shortHandedShotsAgainst': 'Shorthanded Shots Against',
  'powerPlaySaves': 'Power Play Saves',
  'powerPlayShotsAgainst': 'Power Play Shots Against',
  'powerPlaySavePercentage': 'Power Play Save%',
  'evenSaves': 'Even Strength Saves',
  'shortHandedShots': 'Shorthanded Shots Against',
  'shortHandedSavePercentage': 'Shorthanded Save%',
  'powerPlayShots': 'Power Play Shots Against',
  'evenShots': 'Even Strength Shots Against',
  'evenShotsAgainst': 'Even Strength Shots Against',
  'evenStrengthSavePercentage': 'Even Strength Save%',
  'shotsAllowed': 'Shots Against Per Game',
  'shotsAgainst': 'Shots Against',
  'shotsAgainstPerGame': 'Shots Against Per Game',
  'shotsFor': 'Shots For',
  'shotsPerGame': 'Shots Per Game',
  'shotsForPerGame': 'Shots For Per Game',
  'shutouts': 'Shutouts',
  'skaterFullName': 'Player Name',
  'teamAbbrev': 'Team',
  'teamAbbrevs': 'Teams Played For',
  'teamFullName': 'Team',
  'ties': 'Ties',
  'timeOnIcePerGame': 'Time On Ice per Game Played',
  'timeOnIcePerGame5v5': '5v5 Time on Ice per Game',
  'timesShorthanded': 'Times Shorthanded',
  'totalFaceoffLosses': 'Faceoffs Lost',
  'totalFaceoffWins': 'Faceoffs Won',
  'totalFaceoffs': 'Faceoffs',
  'faceoffTaken': 'Faceoffs taken',
  'wins': 'Wins',
  'winsInRegulation': 'Regulation Wins',
  'winsInShootout': 'Shootout Games Won',
  'evGoals': 'Even Strength Goals',
  'evPoints': 'Even Strength Points',
  'blocked': 'Blocked shots',
  'blockedShots': 'Blocked Shots by Player',
  'blockedShotsPer60': 'Blocked Shots per 60',
  'emptyNetAssists': 'Empty Net Assists',
  'emptyNetGoals': 'Empty Net Goals',
  'emptyNetPoints': 'Empty Net Points',
  'firstGoals': 'Times Scored First Goal of Game',
  'giveaways': 'Giveaways',
  'giveawaysPer60': 'Giveaways per 60',
  'hits': 'Hits',
  'hitsPer60': 'Hits per 60',
  'missedShotCrossbar': 'Missed Shot Hit Crossbar',
  'missedShotGoalpost': 'Missed Shots Hit Post',
  'missedShotOverNet': 'Missed Shots Over Net',
  'missedShotWideOfNet': 'Missed Shots Wide of Net',
  'missedShots': 'Missed Shots',
  'takeaways': 'Takeaways',
  'takeawaysPer60': 'Takeaways per 60',
  'ppAssists': 'Power Play Assists',
  'powerPlayAssists': 'Power Play Assists',
  'ppGoalsForPer60': 'Power Play Goals For per 60 minutes',
  'ppGoalsPer60': 'Power Play Goals per 60',
  'ppIndividualSatFor': 'Power Play Individual SAT For',
  'ppIndividualSatForPer60': 'Power Play Individual SAT For per 60',
  'ppPointsPer60': 'Power Play Points per 60',
  'ppPrimaryAssists': 'Power Play Primary Assists',
  'ppPrimaryAssistsPer60': 'Power Play Primary Assists per 60',
  'ppSecondaryAssists': 'Power Play Secondary Assists',
  'ppSecondaryAssistsPer60': 'Power Play Secondary Assists per 60',
  'ppShootingPct': 'Power Play Shooting Pct',
  'ppShots': 'Power Play Shots',
  'ppShotsPer60': 'Power Play Shots per 60',
  'ppTimeOnIce': 'Power Play Time On Ice',
  'ppTimeOnIcePctPerGame': 'Player\'s % of Team Power Play Time, per Game',
  'ppTimeOnIcePerGame': 'Power Play Time On Ice per Game Played',
  'evenTimeOnIce': 'Even Strength Time On Ice',
  'evTimeOnIce': 'Even Strength Time On Ice',
  'evenTimeOnIcePerGame': 'Even Strength Time On Ice Per Game Played',
  'evTimeOnIcePerGame': 'Even Strength Time On Ice Per Game Played',
  'otTimeOnIce': 'Overtime Time on Ice',
  'otTimeOnIcePerOtGame': 'Overtime Time on Ice Per Overtime Game Played',
  'shTimeOnIce': 'Shorthanded Time On Ice',
  'shTimeOnIcePerGame': 'Shorthanded Time On Ice Per Game Played',
  'shifts': 'Shifts',
  'timeOnIce': 'Time On Ice',
  'timeOnIcePerShift': 'Time On Ice Per Shift',
  'faceOffPct': 'Faceoff %',
  'goalsBackhand': 'Backhand Goals',
  'goalsDeflected': 'Goals Deflected',
  'goalsSlap': 'Slap Shot Goals',
  'goalsSnap': 'Snap Shot Goals',
  'goalsTipIn': 'Goals Tipped',
  'goalsWrapAround': 'Wrap Around Goals',
  'goalsWrist': 'Wrist Shot Goals',
  'shootingPctBackhand': 'Shooting Pct Backhand',
  'shootingPctDeflected': 'Shooting Pct Deflected',
  'shootingPctSlap': 'Shooting Pct Slap',
  'shootingPctSnap': 'Shooting Pct Snap',
  'shootingPctTipIn': 'Shooting Pct Tip-In',
  'shootingPctWrapAround': 'Shooting Pct WrapAround',
  'shootingPctWrist': 'Shooting Pct Wrist',
  'shotsOnNetBackhand': 'Backhand Shots',
  'shotsOnNetDeflected': 'Shots Deflected',
  'shotsOnNetSlap': 'Slap Shots',
  'shotsOnNetSnap': 'Snap Shots',
  'shotsOnNetTipIn': 'Shots Tipped',
  'shotsOnNetWrapAround': 'Wrap Around Shots',
  'shotsOnNetWrist': 'Wrist Shots',
  'evenStrengthGoalDifference': 'On-Ice Even-Strength Goal Differential',
  'evenStrengthGoalsAgainst': 'On-Ice Even Strength Goals Against',
  'evenStrengthGoalsFor': 'On-Ice Even Strength Goals For',
  'evGGARatio': 'Even Strength G/GA Ratio',
  'evenStrengthGoalsForPct': 'Even Strength Goals For Pct',
  'evenStrengthTimeOnIcePerGame': 'Even Strength Time On Ice Per Game',
  'powerPlayGoalFor': 'On-Ice Power Play Goals For',
  'powerPlayGoalsAgainst': 'On-Ice Power Play Goals Against',
  'powerPlayTimeOnIce': 'Power Play Time On Ice',
  'powerPlayTimeOnIcePerGame': 'Power Play Time On Ice Per Game',
  'shortHandedGoalsAgainst': 'On-Ice Shorthanded Goals Against',
  'shortHandedGoalsFor': 'On-Ice Shorthanded Goals For',
  'shortHandedTimeOnIcePerGame': 'Shorthanded Time On Ice Per Game',
  'shortHandedTimeOnIce': 'Shorthanded Time On Ice',
  'evFaceoffsWo': 'Even Strength Faceoffs Won',
  'goalieCatches': 'Goalie Catches',
  'playerShoots': 'Skater Shoots',
  'shFaceoffsWo': 'Shorthanded Faceoffs Won',
  'winsInRegulatio': 'Regulation Wins (a Standings tiebreaker since 2019-20)',
  'penaltyKillNetPct': 'Penalty Kill Net Pct',
  'powerPlayNetPct': 'Power Play Net Pct',
  'lossesScoringFirst': 'Losses When Scoring First',
  'lossesTrailingFirst': 'Losses When Trailing First',
  'otLossesScoringFirst': 'Overtime Losses When Scoring First',
  'otLossesTrailingFirst': 'Overtime Losses When Trailing First',
  'scoringFirstGamesPlayed': 'Scoring First Games Played',
  'tiesScoringFirst': 'Ties When Scoring First',
  'tiesTrailingFirst': 'Ties When Trailing First',
  'trailingFirstGamesPlayed': 'Trailing First Games Played',
  'winPctScoringFirst': 'Win % When Scoring First',
  'winPctTrailingFirst': 'Win % When Trailing First',
  'winScoreFirst': 'Wins When Scoring First',
  'winsScoringFirst': 'Wins When Scoring First',
  'winOppScoreFirst': 'Wins When Trailing First',
  'winsTrailingFirst': 'Wins When Trailing First',
  "lossLeadPeriod1": "Losses After Lead Period 1",
  "lossLeadPeriod2": "Losses After Lead Period 2",
  "lossTrailPeriod1": "Losses After Trail Period 1",
  "lossTrailPeriod2": "Losses After Trail Period 2",
  "otLossLeadPeriod1": "OT Loss After Lead Period 1",
  "otLossLeadPeriod2": "OT Loss After Lead Period 2",
  "otLossTrailPeriod1": "OT Loss After Trail Period 1",
  "otLossTrailPeriod2": "OT Loss After Trail Period 2",
  "period1GoalsAgainst": "Goals Against In Period 1",
  "period1GoalsFor": "Goals For In Period 1",
  "period2GoalsAgainst": "Goals Against In Period 2",
  "period2GoalsFor": "Goals For In Period 2",
  "tiesLeadPeriod1": "Ties Leading After Period 1",
  "tiesLeadPeriod2": "Ties Leading After Period 2",
  "tiesTrailPeriod1": "Ties Trailing After Period 1",
  "tiesTrailPeriod2": "Ties Trailing After Period 2",
  "winPctLeadPeriod1": "Win % After Lead Period 1",
  "winPctLeadPeriod2": "Win % After Lead Period 2",
  "winPctTrailPeriod1": "Win % After Trail Period 1",
  "winPctTrailPeriod2": "Win % After Trail Period 2",
  'winLeadFirstPer': 'Wins After Lead 1st',
  "winsLeadPeriod1": "Wins After Lead Period 1",
  'winLeadSecondPer': 'Wins After Lead 2nd',
  "winsLeadPeriod2": "Wins After Lead Period 2",
  "winsTrailPeriod1": "Wins After Trail Period 1",
  "winsTrailPeriod2": "Wins After Trail Period 2",
  'lossesEvenShots': 'Losses Even Shots',
  'lossesOutshootOpponent': 'Losses Outshot Opponent',
  'lossesOutshotByOpponent': 'Losses Outshot by Opponent',
  'netShotsPerGame': 'Net Shots per Game',
  'otLossesEvenShots': 'Overtime Loss Even Shots',
  'otLossesOutshootOpponent': 'Overtime Loss Outshot Opponent',
  'otLossesOutshotByOpponent': 'Overtime Loss Outshot by Opponent',
  'tiesEvenShots': 'Overtime Loss Even Shots',
  'tiesOutshootOpponent': 'Overtime Loss Outshot Opponent',
  'tiesOutshotByOpponent': 'Overtime Loss Outshot by Opponent',
  'winsEvenShots': 'Wins Even Shots',
  'winOutshootOpp': 'Wins Outshot Opponent',
  'winsOutshootOpponent': 'Wins Outshot Opponent',
  'winOutshotByOpp': 'Wins Outshot by Opponent',
  'winsOutshotByOpponent': 'Wins Outshot by Opponent',
  'faceOffsTaken': 'Faceoffs taken',
  'homeRecord': 'Home record',
  'awayRecord': 'Away record',
  'soRecord': 'Record in games decided by shootout',
  'l10Record': 'Record in last 10 games',
  'streak': 'Streak',
  'gameMisconductPenalties':'Penalties Game Misconduct',
  'majorPenalties':'Penalties Major',
  'matchPenalties':'Penalties Match',
  'minorPenalties':'Penalties Minor',
  'misconductPenalties':'Penalties Misconduct',
  'netPenalties':'Net Penalties',
  'netPenaltiesPer60':'Net Penalties per 60',
  'penalties':'Penalties Taken',
  'penaltiesDrawn':'Penalties Drawn',
  'penaltiesDrawnPer60':'Penalties Drawn per 60',
  'penaltiesTakenPer60':'Penalties Taken per 60',
  'penaltyMinutesPerTimeOnIce':'Penalty Minutes per Time on Ice',
  'penaltySecondsPerGame':'Penalty Minutes per Game',
  'ppGoalsAgainstPer60':'Power Play Goals Against per 60 minutes',
  'shAssists':'Shorthanded Assists (since 1933-34)',
  'shGoalsPer60':'Shorthanded Goals per 60 minutes',
  'shIndividualSatFor':'Shorthanded Individual SAT For (since 2009-10)',
  'shIndividualSatForPer60':'Shorthanded Individual SAT For per 60 minutes (since 2009-10)',
  'shPointsPer60':'Shorthanded Points per 60',
  'shPrimaryAssists':'Shorthanded Primary Assists',
  'shPrimaryAssistsPer60':'Shorthanded Primary Assists per 60 minutes',
  'shSecondaryAssists':'Shorthanded Secondary Assists',
  'shSecondaryAssistsPer60':'Shorthanded Secondary Assists per 60 minutes',
  'shShootingPct':'Shorthanded Shooting Pct',
  'shShots':'Shorthanded Shots',
  'shShotsPer60':'Shorthanded Shots per 60 minutes',
  'shTimeOnIcePctPerGame':'Player\'s % of Team Shorthanded Time, per Game',
  'penaltyShotAttempts':'Penalty Shot Attempts',
  'penaltyShotShootingPct':'Penalty Shot Shooting Pct',
  'penaltyShotsFailed':'Penalty Shots Failed',
  'penaltyShotsGoals':'Penalty Shot Goals',
  'faceoffPct5v5':'Faceoff Win Percentage 5v5',
  'goalsPct':'On-Ice Goals For Pct 5v5',
  'individualSatForPer60':'Individual Shot Attempts For per 60',
  'individualShotsForPer60':'Individual 5v5 Shots For per 60 minutes',
  'onIceShootingPct':'5v5 On-Ice Shooting Percentage',
  'satPct':'Shot Attempts Percentage',
  'usatPct':'Unblocked Shot Attempts Percentage',
  'zoneStartPct':'Percentage of Face-Offs: Offensive Zone',
  'satAgainst':'Shot Attempts Against',
  'satAhead':'Shot Attempts Ahead Differential',
  'satBehind':'Shot Attempts Behind Differential',
  'satClose':'Shot Attempts Close Differential',
  'satFor':'Shot Attempts For',
  'satRelative':'Shot Attempts Relative',
  'satTied':'Shot Attempts Tied Differential',
  'satTotal':'Shot Attempts Differential',
  'usatAgainst':'Unblocked Shot Attempts Against',
  'usatAhead':'Unblocked Shot Attempts Ahead Differential',
  'usatBehind':'Unblocked Shot Attempts Behind Differential',
  'usatClose':'Unblocked Shot Attempts Close Differential',
  'usatFor':'Unblocked Shot Attempts For',
  'usatRelative':'Unblocked Shot Attempts Relative',
  'usatTied':'Unblocked Shot Attempts Tied Differential',
  'usatTotal':'Unblocked Shot Attempts Differential',
  'satPercentage':'SAT Percentage',
  'satPercentageAhead':'SAT Percentage Ahead',
  'satPercentageBehind':'SAT Percentage Behind',
  'satPercentageClose':'SAT Percentage Close',
  'satPercentageTied':'SAT Percentage Tied',
  'shootingPct5v5':'Team\'s 5v5 Shooting % when Player on Ice',
  'skaterSavePct5v5':'Team\'s 5v5 Save % when Player on Ice',
  'skaterShootingPlusSavePct5v5':'Team\'s 5v5 Shooting + Save % when Player on Ice',
  'usatPercentage':'USAT Percentage',
  'usatPercentageAhead':'USAT Percentage Ahead',
  'usatPercentageBehind':'USAT Percentage Behind',
  'usatPercentageTied':'USAT Percentage Tied',
  'usatPrecentageClose':'USAT Percentage Close',
  'zoneStartPct5v5':'Offensive Zone Face-off Percentage',
  'assists5v5':'Assists 5v5',
  'assistsPer605v5':'Assists Per 60 Minutes 5v5',
  'goals5v5':'Goals 5v5',
  'goalsPer605v5':'Goals 5v5 Per 60 Minutes',
  'netMinorPenaltiesPer60':'Net Minor Penalties 5v5 per 60 Minutes 5v5',
  'offensiveZoneStartPct5v5':'Offensive Zone Face-off Percentage 5v5',
  'onIceShootingPct5v5':'On-Ice Shooting Percentage 5v5',
  'points5v5':'Points 5v5',
  'pointsPer605v5':'Points 5v5 Per 60 Minutes 5v5',
  'primaryAssists5v5':'Primary Assists 5v5',
  'primaryAssistsPer605v5':'Primary Assists per 60 Minutes 5v5',
  'satRelative5v5':'Shot Attempts Relative Percentage',
  'secondaryAssists5v5':'Secondary Assists 5v5',
  'secondaryAssistsPer605v5':'Secondary Assists per 60 Minutes 5v5',
  'assistsPerGame':'Assists per Game Played',
  'blocksPerGame':'Blocked Shots per Game Played',
  'hitsPerGame':'Hits per Game Played',
  'penaltyMinutesPerGame':'Penalty Minutes Per Game Played',
  'primaryAssistsPerGame':'Primary Assists per Game Played',
  'secondaryAssistsPerGame':'Secondary Assists per Game Played',
  'totalPrimaryAssists':'Primary Assists',
  'totalSecondaryAssists':'Secondary Assists',
  'goalsAgainstAverage':'Goals Against Average',
  'completeGamePct':'Complete Game Percentage',
  'completeGames':'Complete Games When Starter',
  'goalsAgainstPerRegulationLoss':'Goals Against per Regulation Plus Overtime Losses',
  'goalsForAverage':'Goals For Average',
  'incompleteGames':'Incomplete Games When Starter',
  'qualityStart':'Games Started > .900 Save Percentage',
  'qualityStartsPct':'Percentage of Games Started with > .900 Save Percentage',
  'regulationLosses':'Regulation Losses Plus Overtime Losses',
  'regulationWins':'Regulation Wins Plus Overtime Wins',
  'shotsAgainstPer60':'Shots Against Per 60 Minutes',
  'gamesPlayedDaysRest0':'Games Played 0 Days Rest',
  'gamesPlayedDaysRest1':'Games Played 1 Day Rest',
  'gamesPlayedDaysRest2':'Games Played 2 Days Rest',
  'gamesPlayedDaysRest3':'Games Played 3 Days Rest',
  'gamesPlayedDaysRest4Plus':'Games Played 4 or More Days Rest',
  'savePctDaysRest0':'Save Percentage 0 Days Rest',
  'savePctDaysRest1':'Save Percentage 1 Day Rest',
  'savePctDaysRest2':'Save Percentage 2 Days Rest',
  'savePctDaysRest3':'Save Percentage 3 Days Rest',
  'savePctDaysRest4Plus':'Save Percentage 4 or More Days Rest',
  'penaltyShotSavePct':'Penalty Shot Save Percentage',
  'penaltyShotsAgainst':'Penalty Shot Shots Against',
  'penaltyShotsGoalsAgainst':'Penalty Shot Goals Against',
  'penaltyShotsSaves':'Penalty Shot Saves',
  'evGoalsAgainst':'Even Strength Goals Against',
  'evSavePct':'Even Strength Save Percentage',
  'evSaves':'Even Strength Saves',
  'evShotsAgainst':'Even Strength Shots Against',
  'ppSavePct':'Power Play Save Percentage',
  'ppSaves':'Power Play Saves',
  'ppShotsAgainst':'Power Play Shots Against',
  'shGoalsAgainst':'Shorthanded Goals Against (since 1933-34)',
  'shSavePct':'Shorthanded Save Percentage',
  'shSaves':'Shorthanded Saves',
  'shShotsAgainst':'Shorthanded Shots Against',
  'gamesRelieved':'Games Relieved',
  'gamesRelievedGoalsAgainst':'Games Relieved Goals Against',
  'gamesRelievedLosses':'Games Relieved Losses',
  'gamesRelievedOtLosses':'Games Relieved OT Losses',
  'gamesRelievedSavePct':'Games Relieved Save Percentage',
  'gamesRelievedSaves':'Games Relieved Saves',
  'gamesRelievedShotsAgainst':'Games Relieved Shots Against',
  'gamesRelievedTies':'Games Relieved Ties',
  'gamesRelievedWins':'Games Relieved Wins',
  'gamesStartedGoalsAgainst':'Games Started Goals Against',
  'gamesStartedLosses':'Games Started Losses',
  'gamesStartedOtLosses':'Games Started OT Losses',
  'gamesStartedSavePct':'Games Started Save Percentage',
  'gamesStartedSaves':'Games Started Saves',
  'gamesStartedShotsAgainst':'Games Started Shots Against',
  'gamesStartedTies':'Games Started Ties',
  'gamesStartedWins':'Games Started Wins',
  'birthCity':'Player Birth City',
  'birthCountryCode':'Player Birth Country',
  'birthStateProvinceCode':'Player Birth State (USA) or Province (CAN)',
  'draftOverall':'Player Draft Overall Pick No',
  'draftRound':'Player Draft Round No',
  'draftYear':'Player Draft Year',
  'firstSeasonForGameType':'First Season For Game Type',
  'height':'Player Height',
  'isInHallOfFameYn':'In Hall of Fame',
  'nationalityCode':'Player Nationality',
  'weight':'Player Weight',
  "daysRest":"Days Between Games (\'0\' = Back-to-Back Games, \'4\' = 4 or more days)",
  "netGoalsPerGame":"Net Goals per Game Played",
  "ppOpportunitiesPerGame":"Power Play Opportunities per Game Played",
  "shotDifferentialPerGame":"Shot Differential per Game",
  "timesShorthandedPerGame":"Times Shorthanded per Game Played",
  "goalsAgainst3On3":"Goals Against 3v3",
  "goalsAgainst3On4":"Goals Against 3v4",
  "goalsAgainst3On5":"Goals Against 3v5",
  "goalsAgainst3On6":"Goals Against 3v6",
  "goalsAgainst4On3":"Goals Against 4v3",
  "goalsAgainst4On4":"Goals Against 4v4",
  "goalsAgainst4On5":"Goals Against 4v5",
  "goalsAgainst4On6":"Goals Against 4v6",
  "goalsAgainst5On3":"Goals Against 5v3",
  "goalsAgainst5On4":"Goals Against 5v4",
  "goalsAgainst5On5":"Goals Against 5v5",
  "goalsAgainst5On6":"Goals Against 5v6",
  "goalsAgainst6On3":"Goals Against 6v3",
  "goalsAgainst6On4":"Goals Against 6v4",
  "goalsAgainst6On5":"Goals Against 6v5",
  "goalsAgainstPenaltyShots":"Penalty Shot Goals Against",
  "evGoalsFor":"Even Strength Goals For",
  "period3GoalsAgainst":"Goals Against In Period 3",
  "period3GoalsFor":"Goals For In Period 3",
  "periodOtGoalsAgainst":"Goals Against In Overtime",
  "periodOtGoalsFor":"Goals For In OT",
  "ppGoalsFor":"Power Play Goals For",
  "shGoalsFor":"Shorthanded Goals For",
  "goalsFor3On3":"Goals For 3v3",
  "goalsFor3On4":"Goals For 3v4",
  "goalsFor3On5":"Goals For 3v5",
  "goalsFor3On6":"Goals For 3v6",
  "goalsFor4On3":"Goals For 4v3",
  "goalsFor4On4":"Goals For 4v4",
  "goalsFor4On5":"Goals For 4v5",
  "goalsFor4On6":"Goals For 4v6",
  "goalsFor5On3":"Goals For 5v3",
  "goalsFor5On4":"Goals For 5v4",
  "goalsFor5On5":"Goals For 5v5",
  "goalsFor5On6":"Goals For 5v6",
  "goalsFor6On3":"Goals For 6v3",
  "goalsFor6On4":"Goals For 6v4",
  "goalsFor6On5":"Goals For 6v5",
  "goalsForPenaltyShots":"Penalty Shot Goals For",
  "benchMinorPenalties":"Bench Minor Penalties",
  "gameMisconducts":"Game Misconducts",
  "majors":"Major Penalties",
  "minors":"Minor Penalties",
  "misconducts":"Misconduct Penalties",
  "totalPenaltiesDrawn":"Total Penalties Drawn",
  "pkNetGoals":"Short Handed Net Goals",
  "pkNetGoalsPerGame":"Short Handed Net Goals per Game",
  "pkTimeOnIcePerGame":"Penalty Kill Time on Ice per Game",
  "pointsPct":"Point Percentage",
  "ppGoalsAgainstPerGame":"Power Play Goals Against per Game",
  "shGoalsForPerGame":"Shorthanded Goals For per Game",
  "goalsAgainst3v4":"Goals Against 3v4",
  "goalsAgainst3v5":"Goals Against 3v5",
  "goalsAgainst4v5":"Goals Against 4v5",
  "overallPenaltyKillPct":"Penalty Kill Percentage",
  "penaltyKillPct3v4":"Three-vs-Four Penalty Kill Percentage",
  "penaltyKillPct3v5":"Three-vs-Five Penalty Kill Percentage",
  "penaltyKillPct4v5":"Four-vs-Five Penalty Kill Percentage",
  "shorthandedGoalsAgainst":"Shorthanded Goals Against",
  "timeOnIce3v4":"Time on Ice Three-vs-Four",
  "timeOnIce3v5":"Time on Ice Three-vs-Five",
  "timeOnIce4v5":"Time on Ice Four-vs-Five",
  "timeOnIceShorthanded":"Shorthanded Time On Ice",
  "timesShorthanded3v4":"Times Shorthanded Three-vs-Four",
  "timesShorthanded3v5":"Times Shorthanded Three-vs-Five",
  "timesShorthanded4v5":"Times Shorthanded Four-vs-Five",
  "powerPlayGoalsFor":"Power Play Goals For",
  "ppGoalsPerGame":"Power Play Goals per Game",
  "ppNetGoals":"Power Play Net Goals",
  "ppNetGoalsPerGame":"Power Play Net Goals per Game",
  "shGoalsAgainstPerGame":"Shorthanded Goals Against per Game",
  "goals4v3":"Goals Four-vs-Three",
  "goals5v3":"Goals Five-vs-Three",
  "goals5v4":"Goals Five-vs-Four",
  "opportunities4v3":"Opportunities Four-vs-Three",
  "opportunities5v3":"Opportunities Five-vs-Three",
  "opportunities5v4":"Opportunities Five-vs-Four",
  "overallPowerPlayPct":"Power Play Percentage",
  "powerPlayPct4v3":"Four-vs-Three Power Play Percentage",
  "powerPlayPct5v3":"Five-vs-Three Power Play Percentage",
  "powerPlayPct5v4":"Five-vs-Four Power Play Percentage",
  "timeOnIce4v3":"Time on Ice Four-vs-Three",
  "timeOnIce5v3":"Time on Ice Five-vs-Three",
  "timeOnIce5v4":"Time on Ice  Five-vs-Four",
  "timeOnIcePp":"Power Play Time On Ice",
  'shots5v5':'Shots on Net 5v5',
  "goalsForPct":"Goals For Percentage",
  "onIceGoalsAgainst":"Goals Against",
  "onIceGoalsFor":"Goals For",
  "satPctAhead":"Shot Attempts Percentage - Ahead",
  "satPctBehind":"Shot Attempts Percentage - Behind",
  "satPctClose":"Shot Attempts Percentage - Close",
  "satPctTied":"Shot Attempts Percentage - Tied",
  "savePct5v5":"5v5 Save Percentage",
  "shootingPlusSavePct5v5":"5v5 Shooting Plus Save Percentage",
  "usatPctAhead":"Unblocked Shot Attempts Percentage - Ahead",
  "usatPctBehind":"Unblocked Shot Attempts Percentage - Behind",
  "usatPctClose":"Unblocked Shot Attempts Percentage - Close",
  "usatPctTied":"Unblocked Shot Attempts Percentage - Tied",
  'shotsOnNet':'Shots',
  "lossesOneGoalGames":"Loss 1 Goal Game",
  "lossesThreeGoalGames":"Loss 3 Goal Game",
  "lossesTwoGoalGames":"Loss 2 Goal Game",
  "otLossesOneGoalGames":"Overtime Loss 1 Goal Game",
  "winPctOneGoalGames":"Win Percentage 1 Goal Game",
  "winPctThreeGoalGames":"Win Percentage 3 Goal Game",
  "winPctTwoGoalGames":"Win Percentage 2 Goal Game",
  "winsOneGoalGames":"Wins 1 Goal Game",
  "winsThreeGoalGames":"Wins 3 Goal Game",
  "winsTwoGoalGames":"Wins 2 Goal Game",
};

String changeNameToAbb(String teamName) {
  switch (teamName) {
    case 'Anaheim Ducks':
      return 'ANA';

    case 'Arizona Coyotes':
      return 'ARI';

    case 'Boston Bruins':
      return 'BOS';

    case 'Buffalo Sabres':
      return 'BUF';

    case 'Carolina Hurricanes':
      return 'CAR';

    case 'Columbus Blue Jackets':
      return 'CBJ';

    case 'Calgary Flames':
      return 'CGY';

    case 'Chicago Blackhawks':
      return 'CHI';

    case 'Colorado Avalanche':
      return 'COL';

    case 'Dallas Stars':
      return 'DAL';

    case 'Detroit Red Wings':
      return 'DET';

    case 'Edmonton Oilers':
      return 'EDM';

    case 'Florida Panthers':
      return 'FLA';

    case 'Los Angeles Kings':
      return 'LAK';

    case 'Minnesota Wild':
      return 'MIN';

    case 'Montréal Canadiens':
      return 'MTL';

    case 'Nashville Predators':
      return 'NAS';

    case 'New Jersey Devils':
      return 'NJD';

    case 'New York Islanders':
      return 'NYI';

    case 'New York Rangers':
      return 'NYR';

    case 'Ottawa Senators':
      return 'OTT';

    case 'Philadelphia Flyers':
      return 'PHI';

    case 'Pittsburgh Penguins':
      return 'PIT';

    case 'San Jose Sharks':
      return 'SJS';

    case 'St. Louis Blues':
      return 'STL';

    case 'Tampa Bay Lightning':
      return 'TBL';

    case 'Toronto Maple Leafs':
      return 'TOR';

    case 'Vancouver Canucks':
      return 'VAN';

    case 'Vegas Golden Knights':
      return 'VGK';

    case 'Washington Capitals':
      return 'WSH';

    case 'Winnipeg Jets':
      return 'WPG';

    default:
      return 'UNK';
  }
}

Color getTeamColor(String teamName) {
  switch (teamName) {
    case 'Anaheim Ducks':
      return Color(0xFF000000);

    case 'Arizona Coyotes':
      return Color(0xFF862633);

    case 'Boston Bruins':
      return Color(0xFF000000);

    case 'Buffalo Sabres':
      return Color(0xFF041E42);

    case 'Carolina Hurricanes':
      return Color(0xFFC8102E);

    case 'Columbus Blue Jackets':
      return Color(0xFF041E42);

    case 'Calgary Flames':
      return Color(0xFFC8102E);

    case 'Chicago Blackhawks':
      return Color(0xFFC8102E);

    case 'Colorado Avalanche':
      return Color(0xFF6F263D);

    case 'Dallas Stars':
      return Color(0xFF006341);

    case 'Detroit Red Wings':
      return Color(0xFFC8102E);

    case 'Edmonton Oilers':
      return Color(0xFFFC4C02);

    case 'Florida Panthers':
      return Color(0xFFC8102E);

    case 'Los Angeles Kings':
      return Color(0xFF000000);

    case 'Minnesota Wild':
      return Color(0xFF154734);

    case 'Montréal Canadiens':
      return Color(0xFFA6192E);

    case 'Nashville Predators':
      return Color(0xFFFFB81C);

    case 'New Jersey Devils':
      return Color(0xFFC8102E);

    case 'New York Islanders':
      return Color(0xFF003087);

    case 'New York Rangers':
      return Color(0xFF0033A0);

    case 'Ottawa Senators':
      return Color(0xFFC8102E);

    case 'Philadelphia Flyers':
      return Color(0xFFFA4616);

    case 'Pittsburgh Penguins':
      return Color(0xFF000000);

    case 'San Jose Sharks':
      return Color(0xFF006272);

    case 'St. Louis Blues':
      return Color(0xFF003087);

    case 'Tampa Bay Lightning':
      return Color(0xFF00205B);

    case 'Toronto Maple Leafs':
      return Color(0xFF00205B);

    case 'Vancouver Canucks':
      return Color(0xFF00205B);

    case 'Vegas Golden Knights':
      return Color(0xFF333F48);

    case 'Washington Capitals':
      return Color(0xFFC8102E);

    case 'Winnipeg Jets':
      return Color(0xFF041E42);

    default:
      return Color(0x50FFFFFF);
  }
}
